apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
  - resources-finalizers.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/furkannarin/argocd-guestbook.git
    targetRevision: HEAD
    path: app-of-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true